In [89]:
import pandas as pd
from pathlib import Path

In [90]:
def load_results_table(results_dir, methods_list, use_coords, use_demographic, file_name="aggregated_results.json"):
    agg_list = []
    for method in methods_list:
        if use_demographic and use_coords:
            folder_name = f"{method}_coords_demographic_radiomics"
        elif use_demographic and not use_coords:
            folder_name = f"{method}_demographic_radiomics"
        elif not use_demographic and use_coords:
            folder_name = f"{method}_coords_radiomics"
        else:
            folder_name = f"{method}_radiomics"
        aggregated_result_dir = Path(results_dir)/folder_name / file_name
        df = pd.read_json(aggregated_result_dir)
        agg_list.append(df)
    final_df = pd.concat(agg_list, ignore_index=True)
    display(final_df)
    print("Average across models:")
    display(pd.DataFrame(final_df.mean(numeric_only=True)).T)

# Five Fold Cross Validation for Center 1 Dataset

In [91]:
print("Radiomics Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=False, use_demographic=False)

Radiomics Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.730931,0.051506,0.749828,0.106449,0.725214,0.060542,0.870588,0.076696,0.542857,0.176485,0.787670,0.029292
1,mil,0.738027,0.074609,0.743428,0.053060,0.718398,0.056684,0.894118,0.049215,0.529487,0.119375,0.796440,0.053100
2,deep_sets,0.718257,0.064060,0.755376,0.112422,0.708543,0.060575,0.870588,0.064438,0.514286,0.146854,0.779460,0.046493
3,graph,0.598183,0.073313,0.660687,0.105494,0.631206,0.065243,0.729412,0.141666,0.428938,0.164714,0.670256,0.076938
4,AdaBoost,0.724924,0.025482,0.715395,0.042106,0.742727,0.059231,0.811765,0.096657,0.615385,0.135300,0.769854,0.024832
5,CatBoost,0.710901,0.054607,0.755721,0.071690,0.721051,0.049159,0.811765,0.076696,0.579487,0.093070,0.761825,0.044938
6,Extra Trees,0.711361,0.060379,0.762950,0.030334,0.715019,0.045642,0.823529,0.093008,0.564103,0.074204,0.763703,0.055473
7,Gradient Boosting,0.690456,0.043876,0.710946,0.053409,0.710635,0.030592,0.776471,0.076696,0.578388,0.065094,0.740415,0.038225
8,Logistic Regression,0.676893,0.056886,0.721450,0.069210,0.716311,0.050189,0.729412,0.106858,0.610440,0.106159,0.718455,0.054792
9,MLP,0.697367,0.083526,0.763887,0.116680,0.717677,0.060379,0.776471,0.127526,0.595238,0.091612,0.742888,0.077774
10,Random Forest,0.698472,0.042483,0.780112,0.055768,0.724084,0.044995,0.764706,0.072044,0.611538,0.075521,0.742140,0.044757
11,SVM (RBF kernel),0.771835,0.043099,0.809438,0.059213,0.751711,0.051775,0.905882,0.052613,0.593590,0.127369,0.819640,0.029112
12,XGBoost,0.724924,0.026236,0.759793,0.044830,0.743600,0.046628,0.800000,0.067069,0.629487,0.090926,0.767988,0.023699
13,k-Nearest Neighbors,0.712036,0.056333,0.731033,0.099032,0.691273,0.056278,0.905882,0.067069,0.454762,0.133721,0.782200,0.041605
14,lightGBM,0.690671,0.042328,0.733366,0.062323,0.721034,0.025854,0.752941,0.113149,0.612821,0.068082,0.732460,0.052825

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.706349,0.053248,0.743561,0.072135,0.715899,0.050918,0.814902,0.085427,0.564054,0.111233,0.75836,0.046257

In [92]:
print("Radiomics + demographic Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=False, use_demographic=True)

Radiomics + demographic Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.751175,0.053519,0.866042,0.031472,0.773856,0.046742,0.800000,0.067069,0.686630,0.078077,0.785600,0.046749
1,mil,0.784509,0.043070,0.860924,0.028981,0.773158,0.027875,0.882353,0.041595,0.653114,0.064329,0.824024,0.032228
2,deep_sets,0.764279,0.071133,0.837169,0.045909,0.761297,0.054570,0.858824,0.078920,0.635348,0.108717,0.806100,0.056769
3,graph,0.751146,0.053831,0.834411,0.066114,0.805583,0.075862,0.752941,0.049215,0.750366,0.110396,0.776328,0.042210
4,AdaBoost,0.744494,0.034297,0.809912,0.052826,0.765441,0.033442,0.800000,0.052613,0.672161,0.062490,0.781251,0.027464
5,CatBoost,0.724709,0.028985,0.850323,0.024507,0.736499,0.030654,0.811765,0.087249,0.610623,0.085979,0.769582,0.033249
6,Extra Trees,0.718257,0.035874,0.811522,0.004388,0.723515,0.038273,0.823529,0.058824,0.580769,0.064994,0.768949,0.031748
7,Gradient Boosting,0.737367,0.049619,0.849030,0.037066,0.757563,0.044551,0.800000,0.067069,0.654396,0.094094,0.776627,0.040272
8,Logistic Regression,0.738057,0.064665,0.804029,0.042716,0.772959,0.068954,0.776471,0.105227,0.691392,0.111048,0.770214,0.060093
9,MLP,0.750716,0.083741,0.814383,0.102454,0.766726,0.048792,0.811765,0.134138,0.672344,0.080847,0.784935,0.078110
10,Random Forest,0.725154,0.022695,0.832488,0.024513,0.743732,0.046553,0.800000,0.067069,0.629487,0.090926,0.767973,0.022789
11,SVM (RBF kernel),0.778272,0.062163,0.845303,0.051103,0.760055,0.067267,0.905882,0.032219,0.608974,0.145613,0.824914,0.040084
12,XGBoost,0.718272,0.036123,0.836490,0.018914,0.744034,0.042092,0.776471,0.076696,0.643773,0.068289,0.757643,0.037959
13,k-Nearest Neighbors,0.725139,0.067134,0.764889,0.063532,0.705074,0.066946,0.905882,0.032219,0.484432,0.165046,0.791315,0.043026
14,lightGBM,0.690686,0.068595,0.800226,0.038551,0.714861,0.053648,0.764706,0.058824,0.591392,0.099994,0.738637,0.053777

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.740149,0.051696,0.827809,0.042203,0.753624,0.049748,0.818039,0.067263,0.63768,0.095389,0.781606,0.043102

In [93]:
print("Radiomics + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=True, use_demographic=False)

Radiomics + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.812095,0.038685,0.882030,0.032446,0.803455,0.052985,0.894118,0.049215,0.705495,0.092136,0.844741,0.029934
1,mil,0.791175,0.059368,0.835725,0.073761,0.775873,0.042286,0.894118,0.076696,0.654212,0.078831,0.829815,0.049596
2,deep_sets,0.791850,0.044612,0.860978,0.056399,0.775813,0.062421,0.905882,0.032219,0.639927,0.146728,0.833626,0.024540
3,graph,0.725154,0.053059,0.755904,0.066531,0.721272,0.064142,0.858824,0.078920,0.545238,0.160789,0.780846,0.041155
4,AdaBoost,0.751175,0.067312,0.776115,0.057386,0.756268,0.054795,0.835294,0.076696,0.640293,0.089086,0.792809,0.055888
5,CatBoost,0.771175,0.048016,0.818574,0.045896,0.771793,0.052631,0.858824,0.052613,0.655495,0.109332,0.811346,0.032493
6,Extra Trees,0.725154,0.062035,0.788914,0.032189,0.727435,0.059939,0.835294,0.096657,0.580769,0.105682,0.774881,0.056753
7,Gradient Boosting,0.723804,0.061441,0.776966,0.060252,0.728753,0.030238,0.823529,0.117647,0.595055,0.048580,0.770434,0.061849
8,Logistic Regression,0.731146,0.028078,0.795367,0.063195,0.750292,0.030284,0.800000,0.089210,0.642491,0.076361,0.770941,0.035477
9,MLP,0.763834,0.076160,0.802898,0.105786,0.770803,0.040372,0.835294,0.127526,0.669963,0.069602,0.798843,0.073422
10,Random Forest,0.725599,0.049147,0.813257,0.042766,0.753611,0.056139,0.776471,0.076696,0.658974,0.098309,0.762444,0.049345
11,SVM (RBF kernel),0.792065,0.048117,0.827623,0.045992,0.775607,0.062530,0.905882,0.052613,0.641026,0.135376,0.833253,0.033384
12,XGBoost,0.777627,0.055521,0.813542,0.058598,0.782601,0.032213,0.847059,0.089210,0.687729,0.050698,0.811962,0.051388
13,k-Nearest Neighbors,0.704464,0.065251,0.753744,0.083243,0.681442,0.055581,0.917647,0.052613,0.422711,0.130971,0.780797,0.042692
14,lightGBM,0.764509,0.051018,0.794150,0.076309,0.785066,0.024750,0.811765,0.113149,0.705495,0.045367,0.794670,0.056346

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.756722,0.053855,0.806386,0.06005,0.757339,0.048087,0.853333,0.078779,0.629658,0.095857,0.799427,0.046284

In [94]:
print("Radiomics + coords + demographic Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=True, use_demographic=True)

Radiomics + coords + demographic Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.818547,0.040170,0.910149,0.052559,0.793397,0.053054,0.929412,0.049215,0.672344,0.102577,0.854386,0.028481
1,mil,0.811405,0.059006,0.903351,0.056494,0.800496,0.031636,0.894118,0.105227,0.703114,0.062688,0.842385,0.053786
2,deep_sets,0.825643,0.048212,0.909966,0.047602,0.833889,0.042781,0.870588,0.096657,0.768498,0.065482,0.848954,0.047101
3,graph,0.804983,0.070482,0.886705,0.052847,0.825602,0.088014,0.847059,0.052613,0.748168,0.161331,0.833735,0.053241
4,AdaBoost,0.790960,0.049164,0.857240,0.067940,0.787996,0.012529,0.870588,0.113149,0.688828,0.039908,0.823999,0.050233
5,CatBoost,0.750716,0.044861,0.869112,0.015605,0.757902,0.025329,0.835294,0.120552,0.641392,0.084196,0.790015,0.050860
6,Extra Trees,0.731821,0.029557,0.846946,0.007404,0.747374,0.045832,0.811765,0.105227,0.629487,0.105954,0.773403,0.037483
7,Gradient Boosting,0.770701,0.084645,0.859233,0.045777,0.785153,0.050057,0.823529,0.117647,0.701832,0.072716,0.801927,0.076564
8,Logistic Regression,0.738057,0.073285,0.831470,0.053287,0.757563,0.058057,0.800000,0.121979,0.659341,0.091178,0.774367,0.071375
9,MLP,0.784968,0.039456,0.845680,0.097192,0.792469,0.033638,0.847059,0.067069,0.704396,0.055512,0.817477,0.035305
10,Random Forest,0.725154,0.022695,0.846488,0.018503,0.765245,0.064481,0.764706,0.093008,0.675641,0.135346,0.759117,0.028077
11,SVM (RBF kernel),0.804509,0.063828,0.865395,0.044853,0.795685,0.066622,0.894118,0.049215,0.684982,0.131722,0.840564,0.045661
12,XGBoost,0.778057,0.053836,0.866893,0.045754,0.804706,0.052437,0.811765,0.076696,0.734982,0.082024,0.806251,0.047922
13,k-Nearest Neighbors,0.711361,0.084928,0.780748,0.052543,0.688095,0.069493,0.917647,0.032219,0.436996,0.162015,0.785623,0.055274
14,lightGBM,0.771405,0.030912,0.861043,0.052082,0.786786,0.017638,0.823529,0.058824,0.703114,0.031165,0.803850,0.029752

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.774552,0.053003,0.862694,0.047363,0.781491,0.04744,0.849412,0.083953,0.676874,0.092254,0.810404,0.047408

# Second dataset

In [95]:
print("Radiomics Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=False, use_demographic=False, file_name="center2_aggregated_results.json")

Radiomics Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.6225,0.056181,0.655303,0.039032,0.574003,0.050324,0.672222,0.238469,0.581818,0.200464,0.597961,0.129062
1,mil,0.5725,0.066965,0.602652,0.075787,0.498625,0.088716,0.350000,0.295674,0.754545,0.128966,0.377672,0.215320
2,deep_sets,0.5400,0.027099,0.580871,0.062035,0.470926,0.053483,0.377778,0.309694,0.672727,0.225905,0.372665,0.202704
3,graph,0.5600,0.088123,0.579987,0.099053,0.516852,0.072709,0.666667,0.019642,0.472727,0.158603,0.580002,0.049244
4,AdaBoost,0.6025,0.047926,0.637879,0.020076,0.556766,0.060778,0.533333,0.152651,0.659091,0.080353,0.538460,0.104028
5,CatBoost,0.6325,0.014252,0.656313,0.031825,0.566824,0.016828,0.788889,0.086958,0.504545,0.074343,0.657614,0.025705
6,Extra Trees,0.6400,0.051841,0.667740,0.028234,0.592357,0.049503,0.650000,0.135515,0.631818,0.095617,0.614245,0.077679
7,Gradient Boosting,0.5950,0.036012,0.624242,0.054876,0.541928,0.034732,0.683333,0.106863,0.522727,0.105382,0.600648,0.044170
8,Logistic Regression,0.5875,0.030619,0.625758,0.025851,0.567515,0.086208,0.622222,0.274705,0.559091,0.230433,0.541164,0.174445
9,MLP,0.6000,0.066732,0.632828,0.046858,0.517090,0.149848,0.466667,0.339298,0.709091,0.166546,0.455069,0.252004
10,Random Forest,0.6100,0.034686,0.668308,0.018949,0.554101,0.032541,0.683333,0.086958,0.550000,0.060984,0.610321,0.047223
11,SVM (RBF kernel),0.4950,0.011180,0.586742,0.008640,0.123333,0.116428,0.027778,0.027778,0.877273,0.038030,0.045097,0.044511
12,XGBoost,0.6250,0.012500,0.666162,0.024054,0.571361,0.024075,0.694444,0.092128,0.568182,0.095075,0.623127,0.025654
13,k-Nearest Neighbors,0.5625,0.019764,0.630682,0.038862,0.507687,0.011925,0.944444,0.034021,0.250000,0.045455,0.660161,0.013213
14,lightGBM,0.6275,0.038931,0.666667,0.026436,0.576055,0.033168,0.638889,0.109361,0.618182,0.049272,0.603442,0.066501

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.5915,0.040187,0.632142,0.040038,0.515695,0.058751,0.586667,0.153981,0.595455,0.117028,0.525177,0.098098

In [96]:
print("Radiomics + demographic Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=False, use_demographic=True, file_name="center2_aggregated_results.json")

Radiomics + demographic Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.6625,0.063738,0.787879,0.063895,0.716765,0.116798,0.433333,0.298272,0.850000,0.151269,0.492864,0.206395
1,mil,0.6300,0.041079,0.699495,0.088585,0.708459,0.059085,0.333333,0.208796,0.872727,0.099845,0.414759,0.190687
2,deep_sets,0.6225,0.085422,0.639899,0.109195,0.697357,0.184888,0.333333,0.254588,0.859091,0.090053,0.402710,0.221900
3,graph,0.6375,0.082916,0.721212,0.136961,0.537831,0.301087,0.394444,0.357028,0.836364,0.144099,0.407746,0.333549
4,AdaBoost,0.6975,0.047104,0.807576,0.033541,0.629793,0.034960,0.788889,0.122033,0.622727,0.049793,0.698120,0.065298
5,CatBoost,0.7275,0.025617,0.831187,0.026607,0.671653,0.031637,0.777778,0.080985,0.686364,0.063066,0.718658,0.034933
6,Extra Trees,0.6875,0.029315,0.764015,0.035235,0.635420,0.038343,0.733333,0.095420,0.650000,0.087434,0.677009,0.036106
7,Gradient Boosting,0.6750,0.102317,0.792045,0.064137,0.611508,0.088374,0.811111,0.049690,0.563636,0.159415,0.695535,0.073554
8,Logistic Regression,0.6525,0.065192,0.696970,0.028311,0.624003,0.080971,0.638889,0.166667,0.663636,0.174127,0.616767,0.083249
9,MLP,0.6075,0.039131,0.692109,0.030396,0.551538,0.030197,0.633333,0.223434,0.586364,0.121755,0.576238,0.117374
10,Random Forest,0.6975,0.024044,0.786616,0.019446,0.637029,0.037561,0.777778,0.070820,0.631818,0.080993,0.697686,0.022070
11,SVM (RBF kernel),0.5125,0.015309,0.602020,0.013187,0.213810,0.129104,0.033333,0.023241,0.904545,0.033710,0.056799,0.038068
12,XGBoost,0.7500,0.033072,0.852399,0.008899,0.699725,0.050647,0.788889,0.031672,0.718182,0.072940,0.740238,0.024784
13,k-Nearest Neighbors,0.5625,0.026517,0.637374,0.034226,0.507734,0.016372,0.938889,0.045644,0.254545,0.051826,0.658760,0.020328
14,lightGBM,0.7475,0.013693,0.832323,0.011663,0.690404,0.023243,0.800000,0.053432,0.704545,0.045455,0.739899,0.018012

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.658,0.046298,0.742875,0.046952,0.608869,0.081551,0.614444,0.138781,0.693636,0.095052,0.572919,0.099087

In [97]:
print("Radiomics + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=True, use_demographic=False, file_name="center2_aggregated_results.json")

Radiomics + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.6200,0.056319,0.708712,0.029964,0.620557,0.060662,0.377778,0.197007,0.818182,0.075378,0.449913,0.162248
1,mil,0.6150,0.058229,0.635101,0.117669,0.592382,0.056878,0.405556,0.364620,0.786364,0.199819,0.409091,0.276135
2,deep_sets,0.5400,0.047104,0.534154,0.065503,0.403008,0.163022,0.194444,0.235702,0.822727,0.119615,0.232597,0.205833
3,graph,0.6025,0.040889,0.611869,0.110607,0.556383,0.040996,0.472222,0.267158,0.709091,0.160223,0.469034,0.240432
4,AdaBoost,0.6750,0.042390,0.739394,0.027976,0.660278,0.037179,0.572222,0.156643,0.759091,0.074689,0.603414,0.103005
5,CatBoost,0.6825,0.024367,0.718939,0.020469,0.612071,0.023801,0.811111,0.077080,0.577273,0.065477,0.695937,0.030263
6,Extra Trees,0.6425,0.054199,0.682260,0.034275,0.601975,0.066632,0.644444,0.066319,0.640909,0.110642,0.619089,0.041331
7,Gradient Boosting,0.6850,0.037914,0.730934,0.031762,0.660563,0.059853,0.633333,0.030429,0.727273,0.080353,0.644818,0.026891
8,Logistic Regression,0.5625,0.023385,0.627841,0.008517,0.512852,0.026810,0.338889,0.263084,0.745455,0.179962,0.366089,0.195391
9,MLP,0.6125,0.017678,0.673422,0.007435,0.560926,0.016085,0.677778,0.232903,0.559091,0.161187,0.592441,0.123199
10,Random Forest,0.6425,0.018957,0.684091,0.016833,0.588926,0.011140,0.677778,0.082402,0.613636,0.039365,0.628587,0.041018
11,SVM (RBF kernel),0.5000,0.008839,0.578283,0.010788,0.134921,0.130168,0.027778,0.027778,0.886364,0.027835,0.045906,0.045512
12,XGBoost,0.6675,0.043839,0.752399,0.026111,0.622629,0.032033,0.655556,0.147772,0.677273,0.067036,0.632675,0.087586
13,k-Nearest Neighbors,0.5650,0.024044,0.632513,0.037380,0.509321,0.014780,0.938889,0.045644,0.259091,0.054735,0.660038,0.017821
14,lightGBM,0.6925,0.043839,0.764773,0.024704,0.645464,0.035374,0.711111,0.166203,0.677273,0.095617,0.667080,0.092048

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.620333,0.036133,0.671646,0.038,0.55215,0.051694,0.542593,0.157383,0.683939,0.100796,0.514447,0.112581

In [98]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=True, use_demographic=True, file_name="center2_aggregated_results.json")

Radiomics + demographic + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.7075,0.104058,0.811364,0.050663,0.697839,0.095705,0.583333,0.329257,0.809091,0.102399,0.600086,0.231036
1,mil,0.6700,0.097066,0.741793,0.135507,0.672024,0.201420,0.411111,0.274565,0.881818,0.080993,0.481845,0.274687
2,deep_sets,0.6775,0.063982,0.753030,0.058514,0.724917,0.117390,0.538889,0.203746,0.790909,0.206681,0.586087,0.114762
3,graph,0.7300,0.050467,0.781187,0.022813,0.762785,0.021206,0.583333,0.175682,0.850000,0.057045,0.649487,0.102686
4,AdaBoost,0.7675,0.025921,0.833460,0.019881,0.728927,0.024761,0.772222,0.084254,0.763636,0.044304,0.747752,0.038964
5,CatBoost,0.7275,0.016298,0.825000,0.016313,0.666693,0.010972,0.788889,0.054149,0.677273,0.024896,0.722022,0.024480
6,Extra Trees,0.7025,0.037914,0.785038,0.025130,0.649148,0.026438,0.733333,0.126686,0.677273,0.051826,0.685043,0.068380
7,Gradient Boosting,0.7375,0.082443,0.812247,0.041830,0.688873,0.096104,0.800000,0.036218,0.686364,0.155312,0.736518,0.057236
8,Logistic Regression,0.6500,0.065551,0.694697,0.062447,0.714494,0.112225,0.444444,0.248452,0.818182,0.198782,0.500302,0.186789
9,MLP,0.6400,0.059556,0.711174,0.046104,0.600271,0.053579,0.594444,0.292393,0.677273,0.158603,0.565246,0.176140
10,Random Forest,0.6800,0.048088,0.787311,0.025112,0.617157,0.039847,0.755556,0.077080,0.618182,0.029633,0.679101,0.054401
11,SVM (RBF kernel),0.5150,0.005590,0.601957,0.012351,0.154286,0.145125,0.027778,0.027778,0.913636,0.029633,0.046965,0.046523
12,XGBoost,0.7875,0.019764,0.858838,0.010048,0.754618,0.018588,0.783333,0.063343,0.790909,0.029633,0.767524,0.028804
13,k-Nearest Neighbors,0.5650,0.024044,0.639520,0.026345,0.509321,0.014780,0.938889,0.045644,0.259091,0.054735,0.660038,0.017821
14,lightGBM,0.7800,0.011180,0.854419,0.014064,0.741179,0.021431,0.788889,0.063949,0.772727,0.042519,0.762633,0.021250

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.689167,0.047462,0.766069,0.037808,0.645502,0.066638,0.636296,0.140213,0.732424,0.084466,0.61271,0.096264

# Test Time Adaptation (TTA) on Center 2 data

## TENT method for TTA

In [99]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph"], use_coords=True, use_demographic=True, file_name="tta_tent_center2_aggregated_results.json")

Radiomics + demographic + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.7100,0.018540,0.868308,0.011577,0.614643,0.016645,0.955556,0.015215,0.509091,0.034468,0.747947,0.012873
1,mil,0.7700,0.027386,0.864141,0.011713,0.679620,0.028482,0.927778,0.015215,0.640909,0.043717,0.784338,0.022098
2,deep_sets,0.7725,0.016298,0.857702,0.006570,0.712113,0.026115,0.833333,0.043921,0.722727,0.040656,0.767066,0.017343
3,graph,0.6900,0.073633,0.786111,0.056398,0.610733,0.063226,0.888889,0.039284,0.527273,0.122811,0.722651,0.050765

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.735625,0.033965,0.844066,0.021564,0.654277,0.033617,0.901389,0.028408,0.6,0.060413,0.755501,0.02577

## Norm method for TTA

In [101]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph"], use_coords=True, use_demographic=True, file_name="tta_norm_center2_aggregated_results.json")

Radiomics + demographic + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.7075,0.104058,0.811364,0.050663,0.697839,0.095705,0.583333,0.329257,0.809091,0.102399,0.600086,0.231036
1,mil,0.6700,0.097066,0.741793,0.135507,0.672024,0.201420,0.411111,0.274565,0.881818,0.080993,0.481845,0.274687
2,deep_sets,0.6775,0.063982,0.753030,0.058514,0.724917,0.117390,0.538889,0.203746,0.790909,0.206681,0.586087,0.114762
3,graph,0.7300,0.050467,0.781187,0.022813,0.762785,0.021206,0.583333,0.175682,0.850000,0.057045,0.649487,0.102686

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.69625,0.078893,0.771843,0.066874,0.714391,0.108931,0.529167,0.245813,0.832955,0.11178,0.579376,0.180793