In [8]:
import pandas as pd
import os
from glob import glob
from pathlib import Path

In [17]:
def load_results_table(results_dir, methods_list, use_tda):
    agg_list = []
    for method in methods_list:
        aggregated_result_dir = Path(results_dir)/f"{method}{'_tda_radiomics' if use_tda else '_radiomics'}" / "aggregated_results.json"
        df = pd.read_json(aggregated_result_dir)
        agg_list.append(df)
    final_df = pd.concat(agg_list, ignore_index=True)
    display(final_df)

In [19]:
print("Results with Radiomics Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "ml_models"], use_tda=False)

Results with Radiomics Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.797397,0.092523,0.873885,0.048016,0.804902,0.086552,0.858824,0.067069,0.713553,0.144459,0.830397,0.074092
1,mil,0.790945,0.069057,0.857078,0.032364,0.794365,0.057614,0.858824,0.067069,0.700549,0.095322,0.824682,0.055498
2,deep_sets,0.764034,0.090149,0.853954,0.058092,0.774510,0.081952,0.835294,0.076696,0.668315,0.139652,0.802644,0.071756
3,AdaBoost,0.730931,0.030137,0.810138,0.046309,0.747678,0.011571,0.800000,0.067069,0.640110,0.042639,0.771669,0.030109
4,CatBoost,0.731376,0.024729,0.844290,0.015179,0.744636,0.031585,0.811765,0.087249,0.626007,0.079461,0.773785,0.030568
5,Extra Trees,0.711361,0.037728,0.815907,0.020434,0.720481,0.035195,0.811765,0.076696,0.579487,0.075521,0.761477,0.037475
6,Gradient Boosting,0.750931,0.055031,0.843633,0.048700,0.766976,0.043116,0.811765,0.049215,0.669780,0.074687,0.788497,0.043613
7,Logistic Regression,0.750515,0.079953,0.813467,0.048469,0.779076,0.085464,0.800000,0.089210,0.684249,0.154556,0.785999,0.065789
8,MLP,0.730945,0.049828,0.800970,0.081137,0.746808,0.053632,0.811765,0.096657,0.626190,0.121999,0.774052,0.043416
9,Random Forest,0.724694,0.028679,0.816295,0.030135,0.751805,0.058641,0.788235,0.067069,0.642308,0.132957,0.765714,0.014421
10,SVM (RBF kernel),0.778272,0.051722,0.852262,0.052922,0.764210,0.057956,0.894118,0.049215,0.625641,0.120744,0.822296,0.035700
11,XGBoost,0.731161,0.049368,0.830521,0.032489,0.759232,0.039364,0.776471,0.076696,0.672161,0.058235,0.766369,0.046787
12,k-Nearest Neighbors,0.731821,0.061068,0.791128,0.062379,0.707377,0.063394,0.917647,0.032219,0.485714,0.146854,0.797283,0.039078
13,lightGBM,0.710701,0.049362,0.806927,0.043086,0.743791,0.035015,0.752941,0.049215,0.654396,0.054190,0.748235,0.041260

In [20]:
print("Results with Radiomics + TDA Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "ml_models"], use_tda=True)

Results with Radiomics + TDA Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.743589,0.075560,0.871978,0.046360,0.763106,0.049405,0.800000,0.089210,0.669780,0.074687,0.780282,0.065333
1,mil,0.778732,0.049619,0.861280,0.054621,0.771404,0.043302,0.870588,0.049215,0.655495,0.070775,0.817675,0.041879
2,deep_sets,0.778272,0.066481,0.844010,0.054987,0.780351,0.080877,0.870588,0.076696,0.654212,0.193557,0.818598,0.045590
3,AdaBoost,0.723819,0.049549,0.799752,0.045880,0.755263,0.019955,0.764706,0.083189,0.671062,0.036940,0.758586,0.047162
4,CatBoost,0.717152,0.055797,0.856206,0.025782,0.734059,0.054027,0.800000,0.067069,0.605861,0.116492,0.763855,0.043547
5,Extra Trees,0.745169,0.048840,0.821526,0.027781,0.743799,0.039977,0.847059,0.098431,0.612821,0.068082,0.789598,0.050224
6,Gradient Boosting,0.771390,0.039569,0.842383,0.058997,0.812267,0.067394,0.788235,0.032219,0.749267,0.101859,0.798259,0.026814
7,Logistic Regression,0.737627,0.073716,0.820502,0.053864,0.758298,0.068816,0.800000,0.078920,0.655861,0.115549,0.776983,0.061606
8,MLP,0.757627,0.066645,0.818164,0.100255,0.760109,0.051376,0.847059,0.114668,0.641575,0.098663,0.797934,0.059431
9,Random Forest,0.704909,0.023400,0.818277,0.026770,0.729132,0.039556,0.776471,0.076696,0.610256,0.101193,0.749113,0.027280
10,SVM (RBF kernel),0.771376,0.062018,0.852402,0.049956,0.757716,0.066183,0.894118,0.049215,0.608974,0.145613,0.818248,0.041093
11,XGBoost,0.731161,0.049368,0.844473,0.047869,0.759232,0.039364,0.776471,0.076696,0.672161,0.058235,0.766369,0.046787
12,k-Nearest Neighbors,0.718257,0.064060,0.773190,0.059875,0.696320,0.055983,0.905882,0.052613,0.469048,0.124158,0.786368,0.045974
13,lightGBM,0.744064,0.059554,0.832967,0.038627,0.768497,0.021079,0.788235,0.098431,0.686447,0.020163,0.776823,0.057762